services:
  turtlesim:
    build:
      context: ./docker/turtlesim
      dockerfile: Dockerfile
    container_name: turtlesim_node
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=42
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros2_ws:/ros2_ws

  teleop:
    build:
      context: ./docker/teleop
      dockerfile: Dockerfile
    container_name: turtle_teleop
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=42
    volumes:
      - ./ros2_ws:/ros2_ws
    stdin_open: true
    tty: true
    depends_on:
      - turtlesim

  explorer:
    build:
      context: ./docker/explorer
      dockerfile: Dockerfile
    container_name: explorer
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=42
    volumes:
      - ./ros2_ws:/ros2_ws
    depends_on:
      - turtlesim
